from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable


CORPUS_PATH = Path(__file__).resolve().parents[2] / "data" / "tse_processed_data.json"
PLACEHOLDER_TERMS = {"症状待补充", "功效待补充", "待补充", "未知", ""}


@dataclass(frozen=True)
class TSEFormulaRecord:
    name: str
    ingredients: tuple[str, ...]
    dosage: str
    efficacy: str
    suitable_symptoms: tuple[str, ...]
    contraindications: tuple[str, ...]
    tse_category: str | None
    tse_code: str
    source_catalog: str | None
    data_quality: str
    clinical_ranking_eligible: bool


@dataclass(frozen=True)
class TSEProductRecord:
    name: str
    brand: str | None
    price: float | None
    specification: str | None
    purchase_url: str | None
    description: str | None
    tse_category: str | None
    tse_code: str
    source_catalog: str | None


def _normalize(text: str) -> str:
    return re.sub(r"\s+", "", (text or "").strip().lower())


def _token_match(query: str, target: str) -> bool:
    q, t = _normalize(query), _normalize(target)
    if not q or not t:
        return False
    return q == t or q in t or t in q


@lru_cache(maxsize=1)
def _load_raw() -> dict[str, Any]:
    with CORPUS_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


class TSEKnowledgeRepository:
    """Read-only adapter over the legacy TSE catalog snapshot.

    The source snapshot contains real catalog identifiers/inventory metadata, but the
    efficacy/symptom fields were generated by a legacy category heuristic and are not
    treated as clinically validated knowledge in v2. Therefore symptom matches are
    retrieval signals only and are never independently eligible to become a clinical
    formula recommendation.
    """

    def __init__(self) -> None:
        raw = _load_raw()
        self.formulas = tuple(self._formula_from_dict(x) for x in raw.get("herb_formulas", []))
        self.products = tuple(self._product_from_dict(x) for x in raw.get("products", []))
        self._formula_by_code = {x.tse_code: x for x in self.formulas if x.tse_code}
        self._product_by_code = {x.tse_code: x for x in self.products if x.tse_code}

    @staticmethod
    def _formula_from_dict(x: dict[str, Any]) -> TSEFormulaRecord:
        symptoms = tuple(str(s).strip() for s in (x.get("suitable_symptoms") or []) if str(s).strip())
        efficacy = str(x.get("efficacy") or "").strip()
        has_placeholder = (not symptoms or any(s in PLACEHOLDER_TERMS for s in symptoms) or efficacy in PLACEHOLDER_TERMS)
        quality = "LEGACY_PLACEHOLDER" if has_placeholder else "LEGACY_CATEGORY_INFERENCE"
        # Critical safety boundary: the imported symptom/efficacy metadata is not a
        # curated clinical corpus, so none of these rows may independently drive a recommendation.
        eligible = False
        return TSEFormulaRecord(
            name=str(x.get("name") or "").strip(),
            ingredients=tuple(str(i).strip() for i in (x.get("ingredients") or []) if str(i).strip()),
            dosage=str(x.get("dosage") or "").strip(),
            efficacy=efficacy,
            suitable_symptoms=symptoms,
            contraindications=tuple(str(i).strip() for i in (x.get("contraindications") or []) if str(i).strip()),
            tse_category=(str(x.get("tse_category")).strip() if x.get("tse_category") else None),
            tse_code=str(x.get("tse_code") or "").strip(),
            source_catalog=(str(x.get("source_catalog")).strip() if x.get("source_catalog") else None),
            data_quality=quality,
            clinical_ranking_eligible=eligible,
        )

    @staticmethod
    def _product_from_dict(x: dict[str, Any]) -> TSEProductRecord:
        price = x.get("price")
        try:
            price = float(price) if price is not None else None
        except (TypeError, ValueError):
            price = None
        return TSEProductRecord(
            name=str(x.get("name") or "").strip(), brand=(str(x.get("brand")).strip() if x.get("brand") else None),
            price=price, specification=(str(x.get("specification")).strip() if x.get("specification") else None),
            purchase_url=(str(x.get("purchase_url")).strip() if x.get("purchase_url") else None),
            description=(str(x.get("description")).strip() if x.get("description") else None),
            tse_category=(str(x.get("tse_category")).strip() if x.get("tse_category") else None),
            tse_code=str(x.get("tse_code") or "").strip(),
            source_catalog=(str(x.get("source_catalog")).strip() if x.get("source_catalog") else None),
        )

    def stats(self) -> dict[str, Any]:
        placeholders = sum(1 for f in self.formulas if f.data_quality == "LEGACY_PLACEHOLDER")
        inferred = sum(1 for f in self.formulas if f.data_quality == "LEGACY_CATEGORY_INFERENCE")
        return {
            "formula_rows": len(self.formulas),
            "product_rows": len(self.products),
            "placeholder_formula_rows": placeholders,
            "legacy_inferred_formula_rows": inferred,
            "clinical_ranking_eligible_rows": sum(1 for f in self.formulas if f.clinical_ranking_eligible),
            "corpus_policy": "CATALOG_METADATA_ONLY_UNTIL_CLINICAL_CURATION",
        }

    def get_formula(self, tse_code: str) -> TSEFormulaRecord | None:
        return self._formula_by_code.get(str(tse_code))

    def get_product(self, tse_code: str) -> TSEProductRecord | None:
        return self._product_by_code.get(str(tse_code))

    def search_catalog(self, query: str, *, limit: int = 20) -> list[dict[str, Any]]:
        q = _normalize(query)
        if not q:
            return []
        results: list[tuple[float, str, dict[str, Any]]] = []
        for f in self.formulas:
            score = 0.0
            if _token_match(q, f.name): score += 1.0
            if any(_token_match(q, i) for i in f.ingredients): score += 0.8
            if f.tse_category and _token_match(q, f.tse_category): score += 0.3
            if f.tse_code and _token_match(q, f.tse_code): score += 1.2
            if score:
                results.append((score, f.tse_code, {
                    "kind": "herb_catalog_item", "name": f.name, "tse_code": f.tse_code,
                    "category": f.tse_category, "source_catalog": f.source_catalog,
                    "retrieval_score": round(score, 3), "data_quality": f.data_quality,
                    "clinical_ranking_eligible": f.clinical_ranking_eligible,
                }))
        for p in self.products:
            score = 0.0
            if _token_match(q, p.name): score += 1.0
            if p.description and _token_match(q, p.description): score += 0.5
            if p.tse_code and _token_match(q, p.tse_code): score += 1.2
            if score:
                results.append((score, p.tse_code, {
                    "kind": "product", "name": p.name, "tse_code": p.tse_code,
                    "category": p.tse_category, "source_catalog": p.source_catalog,
                    "retrieval_score": round(score, 3), "data_quality": "CATALOG_METADATA",
                    "clinical_ranking_eligible": False,
                }))
        results.sort(key=lambda x: (-x[0], x[1]))
        return [x[2] for x in results[:limit]]

    def retrieve_symptom_metadata(self, symptoms: Iterable[str], *, limit: int = 10) -> list[dict[str, Any]]:
        """Deterministic retrieval against legacy symptom labels.

        This method is intentionally named metadata retrieval rather than recommendation.
        Returned rows are explicitly ineligible for clinical ranking.
        """
        user = [s.strip() for s in symptoms if s and s.strip()]
        if not user:
            return []
        scored: list[tuple[float, str, TSEFormulaRecord, list[str]]] = []
        for f in self.formulas:
            if f.data_quality == "LEGACY_PLACEHOLDER":
                continue
            matched = [u for u in user if any(_token_match(u, fs) for fs in f.suitable_symptoms)]
            if not matched:
                continue
            coverage = len(set(matched)) / len(set(user))
            specificity = len(set(matched)) / max(1, len(f.suitable_symptoms))
            score = 0.7 * coverage + 0.3 * specificity
            scored.append((score, f.tse_code, f, matched))
        scored.sort(key=lambda x: (-x[0], x[1]))
        return [{
            "name": f.name, "tse_code": f.tse_code, "matched_symptoms": matched,
            "retrieval_score": round(score, 4), "data_quality": f.data_quality,
            "clinical_ranking_eligible": False,
            "safety_flags": ["LEGACY_TSE_METADATA_UNVERIFIED", "DO_NOT_USE_AS_STANDALONE_CLINICAL_RECOMMENDATION"],
        } for score, _, f, matched in scored[:limit]]

    def map_formula_candidate(self, name: str, ingredients: Iterable[str] = ()) -> list[dict[str, Any]]:
        """Map an already-generated formula/herb candidate to purchasable catalog rows.

        Mapping is commercial/catalog provenance only. It does not increase model
        confidence or Xerbs TrustScore.
        """
        terms = [name, *ingredients]
        found: dict[str, dict[str, Any]] = {}
        for term in terms:
            if not term:
                continue
            for item in self.search_catalog(term, limit=10):
                code = item["tse_code"]
                prev = found.get(code)
                if prev is None or item["retrieval_score"] > prev["retrieval_score"]:
                    found[code] = item
        return sorted(found.values(), key=lambda x: (-x["retrieval_score"], x["tse_code"]))[:10]
